# [Info]
site_name: Robert-Sen's website
site_url: https://Robert-Sen.github.io
site_author: Robert Sen
site_description: Robert-Sen's website

# [Navigation]
nav:
  - ESSAY:
    - ESSAY/index.md
  - Notes:
    - NOTES/index.md
    - OS:
      - xv6:
        - Filesystem-ch1: NOTES/OS/Xv6/Filesystem/Filesystem_Hierachy.md
        - Filesystem-ch2: NOTES/OS/Xv6/Filesystem/high_level.md
        - Filesystem-ch3: NOTES/OS/Xv6/Filesystem/low_level.md
    
    - rust:
      - cargo: NOTES/rust/Cargo.md
      - Basics: NOTES/rust/Basic-syntax.md
      - Ownership: NOTES/rust/Ownership.md
      - Struct: NOTES/rust/Structs.md
      - Enum: NOTES/rust/Enum.md
      - Package, creates and module: NOTES/rust/Packages-crates-modules.md
      - Collection: NOTES/rust/Collections.md
      - Error handling: NOTES/rust/Error-handling.md
  
  - Dev:
    - DEV/index.md
    # - rust-xv6:
    #   - DEV/xv6-rust/index.md
    #   - DEV/xv6-rust/23-1.md
    #   - DEV/xv6-rust/23-2.md
    #   - DEV/xv6-rust/23-3.md

  - About:
    - ABOUT/index.md
    - Site build: ABOUT/Site-build.md

# [Ui]
theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'
  language: en
  font: 
    text: Luxurious Roman
    code: Roboto Mono

  palette:
      # 亮色
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: teal
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      # 自动调节
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

      # 暗色
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
      # 向下滚动时固定 tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    - navigation.indexes
      # 只渲染可见的 HTML
    - navigation.prune
    - navigation.top
      # 搜索出的文章关键词加入高亮
    - search.highlight
    - content.code.copy

  plugins:
    - social
    - search:
      jieba_dict: dict.txt

extra_javascript:
  - javascripts/shortcuts.js

extra:
  social:
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/497802803
    #   name: Bilibili | 呆胶布迪斯卡-_-
    - icon: fontawesome/brands/github
      link: https://github.com/Robert-Sen
      name: Github | Robert-Sen

copyright: Copyright &copy; 2024 - 2024 Robert Sen

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all

  - pymdownx.highlight:
      # linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde